version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fullstackhero
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data 